### ISSUE TITLE
no file selection popup in offline_viewer when clicking on File > Open

### ISSUE THREAD

**Issue by VRichardJP** [koide3/glim_ros2#17]
Hello!

I have followed the installation and getting started documentation to run glim on my own data.
I have the mapping results in /tmp/dump/, but I can't manage to open the map with the offline_viewer. When I click on File > Open, I don't see any popup window to select the file:

[glim-2024-07-30_10.56.20.webm](https://github.com/user-attachments/assets/6b02176d-41cf-48ef-b92f-310b2c23f6c8)

Any idea?

**Comment by koide3** [comment]
Should be fixed by https://github.com/koide3/glim/issues/36#issuecomment-2244348365

**Comment by VRichardJP** [comment]
Yes, thank you!
